# 钉钉推送配置示例

# 核心配置
default_timeout: 30s
max_retries: 3
enable_metrics: true
enable_tracing: false

# 钉钉平台配置
dingtalk:
  # 必需：钉钉 Webhook URL（从环境变量获取）
  webhook_url: "${DINGTALK_WEBHOOK_URL}"

  # 可选：签名密钥（用于加签验证）
  secret: "${DINGTALK_SECRET}"

  # 可选：自定义关键词列表
  keywords:
    - "通知"
    - "告警"
    - "监控"

  # 超时设置
  timeout: 30s

  # 重试设置
  max_retries: 3

  # 频率限制（每分钟最大消息数）
  rate_limit: 20

# 重试策略
retry_policy:
  enabled: true
  initial_interval: 1s
  max_interval: 30s
  multiplier: 2.0
  max_retries: 3

# 异步配置
async_config:
  enabled: false
  queue_type: memory
  queue_size: 1000
  workers: 4
  batch_size: 10
  process_timeout: 30s

# 路由配置
router_config:
  enabled: false
  rules: []