package message

import (
	"testing"
	"time"

	"github.com/kart-io/notifyhub/core"
	"github.com/stretchr/testify/assert"
)

func TestNewBuilder(t *testing.T) {
	t.Run("Create new builder", func(t *testing.T) {
		builder := NewBuilder()
		assert.NotNil(t, builder)
		assert.NotNil(t, builder.message)
		assert.Equal(t, core.FormatText, builder.message.Format)
		assert.Equal(t, core.Priority(2), builder.message.Priority)
		assert.NotNil(t, builder.message.Variables)
		assert.NotNil(t, builder.message.Metadata)
		assert.False(t, builder.message.CreatedAt.IsZero())
	})
}

func TestBasicBuilderMethods(t *testing.T) {
	t.Run("Title method", func(t *testing.T) {
		builder := NewBuilder()
		result := builder.Title("Test Title")

		assert.Equal(t, builder, result) // Should return self for chaining
		assert.Equal(t, "Test Title", builder.message.Title)
	})

	t.Run("Body method", func(t *testing.T) {
		builder := NewBuilder()
		result := builder.Body("Test Body")

		assert.Equal(t, builder, result)
		assert.Equal(t, "Test Body", builder.message.Body)
	})

	t.Run("Priority method", func(t *testing.T) {
		builder := NewBuilder()
		result := builder.Priority(5)

		assert.Equal(t, builder, result)
		assert.Equal(t, core.Priority(5), builder.message.Priority)
	})

	t.Run("Format method", func(t *testing.T) {
		builder := NewBuilder()
		result := builder.Format(core.FormatMarkdown)

		assert.Equal(t, builder, result)
		assert.Equal(t, core.FormatMarkdown, builder.message.Format)
	})

	t.Run("AddTarget method", func(t *testing.T) {
		builder := NewBuilder()
		target := core.NewTarget(core.TargetTypeEmail, "test@example.com", "email")

		result := builder.AddTarget(target)
		assert.Equal(t, builder, result)
		assert.Len(t, builder.message.Targets, 1)
		assert.Equal(t, target, builder.message.Targets[0])
	})
}

func TestBuildMethod(t *testing.T) {
	t.Run("Build message", func(t *testing.T) {
		builder := NewBuilder()
		message := builder.
			Title("Test Message").
			Body("Test Body").
			Priority(4).
			Format(core.FormatHTML).
			Build()

		assert.Equal(t, "Test Message", message.Title)
		assert.Equal(t, "Test Body", message.Body)
		assert.Equal(t, core.Priority(4), message.Priority)
		assert.Equal(t, core.FormatHTML, message.Format)
		assert.NotEmpty(t, message.ID) // Should generate ID
	})

	// Note: Custom ID setting is handled by the Build() method automatically
}

func TestAdvancedBuilderMethods(t *testing.T) {
	t.Run("Variable method", func(t *testing.T) {
		builder := NewBuilder()
		result := builder.Variable("name", "John")

		assert.Equal(t, builder, result)
		assert.Equal(t, "John", builder.message.Variables["name"])
	})

	t.Run("Variables method", func(t *testing.T) {
		builder := NewBuilder()
		variables := map[string]interface{}{
			"user":   "Alice",
			"count":  5,
			"active": true,
		}

		result := builder.Variables(variables)
		assert.Equal(t, builder, result)
		assert.Equal(t, "Alice", builder.message.Variables["user"])
		assert.Equal(t, 5, builder.message.Variables["count"])
		assert.Equal(t, true, builder.message.Variables["active"])
	})

	t.Run("Metadata method", func(t *testing.T) {
		builder := NewBuilder()
		result := builder.Metadata("source", "api")

		assert.Equal(t, builder, result)
		assert.Equal(t, "api", builder.message.Metadata["source"])
	})

	t.Run("Template method", func(t *testing.T) {
		builder := NewBuilder()
		result := builder.Template("notification_template")

		assert.Equal(t, builder, result)
		assert.Equal(t, "notification_template", builder.message.Template)
	})

	t.Run("Delay method", func(t *testing.T) {
		builder := NewBuilder()
		delay := 5 * time.Minute
		result := builder.Delay(delay)

		assert.Equal(t, builder, result)
		assert.Equal(t, delay, builder.message.Delay)
	})

	// Note: ID is automatically generated by the Build() method
}

// Note: Platform builders have been replaced by AddTarget() method in the unified API

func TestConvenienceCreators(t *testing.T) {
	t.Run("Quick creator", func(t *testing.T) {
		builder := Quick("Quick Title", "Quick Body")
		message := builder.Build()

		assert.Equal(t, "Quick Title", message.Title)
		assert.Equal(t, "Quick Body", message.Body)
	})

	t.Run("Alert creator", func(t *testing.T) {
		builder := Alert("Alert Title", "Alert Body")
		message := builder.Build()

		assert.Equal(t, "Alert Title", message.Title)
		assert.Equal(t, "Alert Body", message.Body)
		assert.Equal(t, core.Priority(4), message.Priority) // Alert priority
	})

	t.Run("Emergency creator", func(t *testing.T) {
		builder := Emergency("Emergency Title", "Emergency Body")
		message := builder.Build()

		assert.Equal(t, "Emergency Title", message.Title)
		assert.Equal(t, "Emergency Body", message.Body)
		assert.Equal(t, core.Priority(5), message.Priority) // Emergency priority
	})

	t.Run("Notice creator", func(t *testing.T) {
		builder := Notice("Notice Title", "Notice Body")
		message := builder.Build()

		assert.Equal(t, "Notice Title", message.Title)
		assert.Equal(t, "Notice Body", message.Body)
		assert.Equal(t, core.Priority(1), message.Priority) // Notice priority
	})

	t.Run("Markdown creator", func(t *testing.T) {
		builder := Markdown("Markdown Title", "**Bold** text")
		message := builder.Build()

		assert.Equal(t, "Markdown Title", message.Title)
		assert.Equal(t, "**Bold** text", message.Body)
		assert.Equal(t, core.FormatMarkdown, message.Format)
	})

	t.Run("HTML creator", func(t *testing.T) {
		builder := HTML("HTML Title", "<b>Bold</b> text")
		message := builder.Build()

		assert.Equal(t, "HTML Title", message.Title)
		assert.Equal(t, "<b>Bold</b> text", message.Body)
		assert.Equal(t, core.FormatHTML, message.Format)
	})

	t.Run("Card creator", func(t *testing.T) {
		builder := Card("Card Title", "Card content")
		message := builder.Build()

		assert.Equal(t, "Card Title", message.Title)
		assert.Equal(t, "Card content", message.Body)
		assert.Equal(t, core.FormatCard, message.Format)
	})
}

// Note: Builder cloning has been removed from the unified API

func TestBuilderValidation(t *testing.T) {
	t.Run("Valid builder", func(t *testing.T) {
		builder := NewBuilder()
		builder.Title("Valid Title").
			Body("Valid Body").
			Priority(3).
			AddTarget(core.NewTarget(core.TargetTypeEmail, "test@example.com", "email"))

		err := builder.Validate()
		assert.NoError(t, err)
	})

	t.Run("Empty title and body", func(t *testing.T) {
		builder := NewBuilder()
		builder.Priority(3)

		err := builder.Validate()
		assert.Error(t, err)
		assert.Contains(t, err.Error(), "title or body")
	})

	t.Run("Invalid priority", func(t *testing.T) {
		builder := NewBuilder()
		builder.Title("Title").
			Body("Body").
			Priority(10) // Invalid priority

		err := builder.Validate()
		assert.Error(t, err)
		assert.Contains(t, err.Error(), "priority")
	})

	t.Run("Valid with only title", func(t *testing.T) {
		builder := NewBuilder()
		builder.Title("Only Title").
			Priority(3).
			AddTarget(core.NewTarget(core.TargetTypeEmail, "test@example.com", "email"))

		err := builder.Validate()
		assert.NoError(t, err)
	})

	t.Run("Valid with only body", func(t *testing.T) {
		builder := NewBuilder()
		builder.Body("Only Body").
			Priority(3).
			AddTarget(core.NewTarget(core.TargetTypeEmail, "test@example.com", "email"))

		err := builder.Validate()
		assert.NoError(t, err)
	})
}

// Note: NoOpPlatformBuilder has been removed from the unified API

func TestMessageIDGeneration(t *testing.T) {
	t.Run("Generate unique IDs", func(t *testing.T) {
		ids := make(map[string]bool)

		// Generate 100 IDs and ensure they're unique
		for i := 0; i < 100; i++ {
			id := generateMessageID()
			assert.NotEmpty(t, id)
			assert.False(t, ids[id], "Generated duplicate ID: %s", id)
			ids[id] = true
		}
	})

	t.Run("ID format", func(t *testing.T) {
		id := generateMessageID()
		assert.True(t, len(id) > 4) // Should be a reasonable length
		assert.NotEmpty(t, id)      // Should not be empty
	})
}

func TestGetMessage(t *testing.T) {
	t.Run("GetMessage returns current state", func(t *testing.T) {
		builder := NewBuilder()
		builder.Title("Test Title").
			Body("Test Body")

		message := builder.GetMessage()
		assert.Equal(t, "Test Title", message.Title)
		assert.Equal(t, "Test Body", message.Body)

		// Message should be the same instance
		assert.Equal(t, builder.message, message)
	})
}

func TestMessageBuilderInterfaceCompliance(t *testing.T) {
	t.Run("Implements CoreMessageBuilder interface", func(t *testing.T) {
		builder := NewBuilder()

		// Test interface methods
		result := builder.Title("Interface Test")
		assert.NotNil(t, result)

		result = builder.Body("Interface Body")
		assert.NotNil(t, result)

		result = builder.Priority(3)
		assert.NotNil(t, result)

		result = builder.Format(core.FormatText)
		assert.NotNil(t, result)

		target := core.NewTarget(core.TargetTypeEmail, "test@example.com", "email")
		result = builder.AddTarget(target)
		assert.NotNil(t, result)

		message := builder.Build()
		assert.NotNil(t, message)
		assert.Equal(t, "Interface Test", message.Title)
		assert.Equal(t, "Interface Body", message.Body)

		// Note: Platform-specific builders have been replaced by AddTarget() method
	})
}

// Benchmark tests
func BenchmarkBuilderCreation(b *testing.B) {
	for i := 0; i < b.N; i++ {
		NewBuilder()
	}
}

func BenchmarkMessageBuilding(b *testing.B) {
	for i := 0; i < b.N; i++ {
		NewBuilder().
			Title("Benchmark Test").
			Body("Benchmark test body").
			Priority(3).
			Format(core.FormatText).
			Build()
	}
}

// Note: Builder cloning benchmarks removed with unified API

// Note: Platform builder benchmarks removed with unified API
