# NotifyHub HTTP Service Configuration

# Server configuration
server:
  port: 8080
  read_timeout: 10s
  write_timeout: 10s
  max_request_size: 1048576  # 1MB in bytes

# Authentication
auth:
  api_key: "${API_KEY}"  # Set via environment variable

# Rate limiting
rate_limit:
  requests_per_minute: 60

# Logging
logging:
  level: "info"  # debug, info, warn, error
  format: "json"  # json, text

# NotifyHub configuration
notifyhub:
  # Feishu configuration
  feishu:
    webhook_url: "${NOTIFYHUB_FEISHU_WEBHOOK_URL}"
    secret: "${NOTIFYHUB_FEISHU_SECRET}"
    timeout: 30s

  # Email configuration
  email:
    host: "${NOTIFYHUB_SMTP_HOST}"
    port: "${NOTIFYHUB_SMTP_PORT}"
    username: "${NOTIFYHUB_SMTP_USERNAME}"
    password: "${NOTIFYHUB_SMTP_PASSWORD}"
    from: "${NOTIFYHUB_SMTP_FROM}"
    use_tls: true
    timeout: 30s

  # Queue configuration
  queue:
    type: "memory"  # memory, redis
    buffer_size: 1000
    workers: 4
    retry_policy:
      max_retries: 3
      initial_interval: 30s
      multiplier: 2.0
      max_jitter: 2s

  # Telemetry configuration (optional)
  telemetry:
    enabled: false
    service_name: "notifyhub-http-service"
    service_version: "1.0.0"
    environment: "development"
    tracing_enabled: true
    metrics_enabled: true
    otlp_endpoint: "http://localhost:4317"

# Health check configuration
health:
  check_interval: 30s
  timeout: 5s

# Metrics configuration
metrics:
  enabled: true
  path: "/metrics"
  update_interval: 10s