# 企业微信推送配置示例
# WeChat Work Push Configuration Example

platforms:
  wechatwork:
    # 必需：企业微信群机器人 Webhook URL
    # Required: WeChat Work Group Robot Webhook URL
    webhook_url: "${WECHATWORK_WEBHOOK_URL}"

    # 可选：签名密钥（用于签名验证安全模式）
    # Optional: Signature secret (for signature verification security mode)
    secret: "${WECHATWORK_SECRET}"

    # 可选：关键词验证列表（用于关键词验证安全模式）
    # Optional: Keyword verification list (for keyword verification security mode)
    keywords:
      - "通知"
      - "告警"
      - "监控"

    # 可选：请求超时时间
    # Optional: Request timeout
    timeout: "30s"

    # 可选：最大重试次数
    # Optional: Maximum retry attempts
    max_retries: 3

    # 可选：速率限制（每秒最大请求数）
    # Optional: Rate limit (max requests per second)
    rate_limit: 20

# 日志配置
# Logging configuration
logger:
  level: "info"
  format: "json"
  output: "stdout"

# 队列配置
# Queue configuration
queue:
  type: "memory"
  size: 1000
  workers: 4

# 监控配置
# Monitoring configuration
monitoring:
  enabled: true
  metrics_path: "/metrics"
  health_path: "/health"