# NotifyHub Configuration Example
# This file demonstrates the complete configuration structure
# using Viper for unified configuration management

# Service configuration
service:
  name: "notifyhub"
  environment: "production"  # development, staging, production
  version: "1.0.0"
  debug: false
  port: 8080

# Feishu platform configuration
feishu:
  enabled: true
  webhook_url: "https://open.feishu.cn/open-apis/bot/v2/hook/your-webhook-url"
  secret: "your-feishu-secret"
  timeout: "30s"

# Email platform configuration
email:
  enabled: true
  host: "smtp.gmail.com"
  port: 587
  username: "your-email@gmail.com"
  password: "your-app-password"
  from: "noreply@yourcompany.com"
  use_tls: true
  timeout: "30s"

# SMS platform configuration
sms:
  enabled: false
  provider: "twilio"  # twilio, aliyun, etc.
  api_key: "your-sms-api-key"
  api_secret: "your-sms-api-secret"
  from: "+1234567890"
  timeout: "30s"

# Queue configuration
queue:
  type: "memory"  # memory, redis
  size: 1000
  workers: 4
  batch_size: 100
  # Redis configuration (when type: redis)
  redis_url: "redis://localhost:6379"
  redis_db: 0

# HTTP server configuration
http:
  port: 8080
  host: "0.0.0.0"
  read_timeout: "10s"
  write_timeout: "10s"
  shutdown_timeout: "30s"
  cors_enabled: true
  auth_enabled: true
  api_key: "your-api-key"

# Routing configuration
routing:
  enabled: true
  default:
    platform: "feishu"
    targets:
      - "default-channel"
  rules:
    - name: "high-priority-alerts"
      priority: 100
      condition:
        priorities: [4, 5]  # High and critical priority
        keywords: ["error", "critical", "failure"]
      action:
        targets:
          - type: "group"
            value: "alert-channel"
            platform: "feishu"
          - type: "email"
            value: "ops-team@company.com"
            platform: "email"

    - name: "business-hours-notifications"
      priority: 50
      condition:
        time_range:
          start: "09:00"
          end: "18:00"
        weekdays: [1, 2, 3, 4, 5]  # Monday to Friday
      action:
        targets:
          - type: "group"
            value: "business-channel"
            platform: "feishu"

    - name: "off-hours-critical"
      priority: 75
      condition:
        priorities: [5]  # Critical only
        time_range:
          start: "18:01"
          end: "08:59"
      action:
        targets:
          - type: "user"
            value: "oncall-engineer"
            platform: "sms"
          - type: "email"
            value: "oncall@company.com"
            platform: "email"

# Logging configuration
logging:
  level: "info"  # debug, info, warn, error, silent
  format: "json"  # json, text
  output: "stdout"  # stdout, stderr, file
  file: "/var/log/notifyhub/app.log"  # when output: file
  max_size: 100  # MB
  max_backups: 10
  max_age: 30  # days
  compress: true
  slow_threshold: "200ms"  # Log slow operations