# 飞书推送配置示例 - 模板集成版本
# Feishu Push Configuration Example - Template Integration Version

platforms:
  feishu:
    # 必需：飞书群机器人 Webhook URL
    # Required: Feishu Group Robot Webhook URL
    webhook_url: "${FEISHU_WEBHOOK_URL}"

    # 可选：签名密钥（用于签名验证安全模式）
    # Optional: Signature secret (for signature verification security mode)
    secret: "${FEISHU_SECRET}"

    # 可选：关键词验证列表（用于关键词验证安全模式）
    # Optional: Keyword verification list (for keyword verification security mode)
    keywords:
      - "通知"
      - "告警"
      - "监控"

    # 可选：请求超时时间
    # Optional: Request timeout
    timeout: "30s"

    # 可选：最大重试次数
    # Optional: Maximum retry attempts
    max_retries: 3

    # 可选：速率限制（每秒最大请求数）
    # Optional: Rate limit (max requests per second)
    rate_limit: 20

# 模板配置
# Template configuration
templates:
  # 模板引擎配置
  # Template engine configuration
  engines:
    # Go template 引擎
    go:
      enabled: true
      max_template_size: 1048576  # 1MB
      supports_functions: true

    # Mustache 模板引擎
    mustache:
      enabled: true
      max_template_size: 1048576  # 1MB
      supports_partials: true

    # Handlebars 模板引擎
    handlebars:
      enabled: true
      max_template_size: 1048576  # 1MB
      supports_partials: true
      supports_functions: true

  # 缓存配置
  # Cache configuration
  cache:
    enabled: true
    ttl: "5m"
    max_size: 1000

  # 热重载配置
  # Hot reload configuration
  hot_reload:
    enabled: false
    watch_dirs:
      - "./templates"
    watch_extensions:
      - ".tmpl"
      - ".mustache"
      - ".hbs"

  # 模板目录
  # Template directories
  directories:
    - "./templates"

  # 预注册模板
  # Pre-registered templates
  templates:
    alert:
      file: "templates/alert.tmpl"
      engine: "go"
      description: "系统告警消息模板"

    system_status:
      file: "templates/system_status.tmpl"
      engine: "go"
      description: "系统状态报告模板"

    deployment:
      file: "templates/deployment.tmpl"
      engine: "go"
      description: "部署通知模板"

    user_activity:
      file: "templates/user_activity.mustache"
      engine: "mustache"
      description: "用户活动通知模板"

# 日志配置
# Logging configuration
logger:
  level: "info"
  format: "json"
  output: "stdout"

# 队列配置
# Queue configuration
queue:
  type: "memory"
  size: 1000
  workers: 4

# 监控配置
# Monitoring configuration
monitoring:
  enabled: true
  metrics_path: "/metrics"
  health_path: "/health"

# 消息配置
# Message configuration
messages:
  # 默认消息格式
  default_format: "markdown"

  # 消息验证
  validation:
    enabled: true
    max_title_length: 100
    max_body_length: 4096

  # 消息重试
  retry:
    enabled: true
    max_attempts: 3
    backoff_multiplier: 2.0
    initial_delay: "1s"